MODEL (
  name base.players_averages,
  kind FULL,
);

SELECT
    -- Grouping Keys
    PLAYER_ID,
    SEASON_ID,
    TEAM_ID,

    COUNT(*) AS GAMES_PLAYED,

    -- Metadata
    ANY_VALUE(PLAYER_NAME) AS PLAYER_NAME,
    ANY_VALUE(NICKNAME) AS NICKNAME,
    ANY_VALUE(TEAM_ABBREVIATION) AS TEAM_ABBREVIATION,
    ANY_VALUE(TEAM_NAME) AS TEAM_NAME,
    ANY_VALUE(TEAM_CITY) AS TEAM_CITY,
    ANY_VALUE(START_POSITION) AS START_POSITION,

    -- Average Minutes
    AVG(
        CASE 
            WHEN MIN IS NULL THEN 0
            ELSE CAST(SPLIT_PART(MIN, ':', 1) AS DOUBLE) + CAST(SPLIT_PART(MIN, ':', 2) AS DOUBLE) / 60
        END
    ) AS AVG_MINUTES,

    -- Core Box Score Averages
    AVG(PTS) AS AVG_PTS,
    AVG(AST) AS AVG_AST,
    AVG(REB) AS AVG_REB,
    AVG(OREB) AS AVG_OREB,
    AVG(DREB) AS AVG_DREB,
    AVG(STL) AS AVG_STL,
    AVG(COALESCE(BLK, 0)) AS AVG_BLK,
    AVG(COALESCE(PF, 0)) AS AVG_PF,
    AVG("TO") AS AVG_TO,
    AVG(FGM) AS AVG_FGM,
    AVG(FGA) AS AVG_FGA,
    AVG(FG3M) AS AVG_FG3M,
    AVG(FG3A) AS AVG_FG3A,
    AVG(FTM) AS AVG_FTM,
    AVG(FTA) AS AVG_FTA,
    AVG(PLUS_MINUS) AS AVG_PLUS_MINUS,

    -- Averages from Misc
    AVG(PTS_OFF_TOV) AS AVG_PTS_OFF_TOV,
    AVG(PTS_2ND_CHANCE) AS AVG_PTS_2ND_CHANCE,
    AVG(PTS_FB) AS AVG_PTS_FB,
    AVG(PTS_PAINT) AS AVG_PTS_PAINT,
    AVG(OPP_PTS_OFF_TOV) AS AVG_OPP_PTS_OFF_TOV,
    AVG(OPP_PTS_2ND_CHANCE) AS AVG_OPP_PTS_2ND_CHANCE,
    AVG(OPP_PTS_FB) AS AVG_OPP_PTS_FB,
    AVG(OPP_PTS_PAINT) AS AVG_OPP_PTS_PAINT,
    AVG(BLKA) AS AVG_BLKA,
    AVG(PFD) AS AVG_PFD,

    -- Advanced Stats (non-summed)
    AVG(E_OFF_RATING) AS AVG_E_OFF_RATING,
    AVG(OFF_RATING) AS AVG_OFF_RATING,
    AVG(E_DEF_RATING) AS AVG_E_DEF_RATING,
    AVG(DEF_RATING) AS AVG_DEF_RATING,
    AVG(E_NET_RATING) AS AVG_E_NET_RATING,
    AVG(NET_RATING) AS AVG_NET_RATING,
    AVG(AST_PCT) AS AVG_AST_PCT,
    AVG(AST_TOV) AS AVG_AST_TOV,
    AVG(AST_RATIO) AS AVG_AST_RATIO,
    AVG(OREB_PCT) AS AVG_OREB_PCT,
    AVG(DREB_PCT) AS AVG_DREB_PCT,
    AVG(REB_PCT) AS AVG_REB_PCT,
    AVG(TM_TOV_PCT) AS AVG_TM_TOV_PCT,
    AVG(EFG_PCT) AS AVG_EFG_PCT,
    AVG(TS_PCT) AS AVG_TS_PCT,
    AVG(USG_PCT) AS AVG_USG_PCT,
    AVG(E_USG_PCT) AS AVG_E_USG_PCT,
    AVG(E_PACE) AS AVG_E_PACE,
    AVG(PACE) AS AVG_PACE,
    AVG(PACE_PER40) AS AVG_PACE_PER40,
    AVG(POSS) AS AVG_POSS,
    AVG(PIE) AS AVG_PIE,

    -- Opponent Four Factors
    AVG(FTA_RATE) AS AVG_FTA_RATE,
    AVG(OPP_EFG_PCT) AS AVG_OPP_EFG_PCT,
    AVG(OPP_FTA_RATE) AS AVG_OPP_FTA_RATE,
    AVG(OPP_TOV_PCT) AS AVG_OPP_TOV_PCT,
    AVG(OPP_OREB_PCT) AS AVG_OPP_OREB_PCT,

    -- Scoring Distribution Averages
    AVG(PCT_FGA_2PT) AS AVG_PCT_FGA_2PT,
    AVG(PCT_FGA_3PT) AS AVG_PCT_FGA_3PT,
    AVG(PCT_PTS_2PT) AS AVG_PCT_PTS_2PT,
    AVG(PCT_PTS_2PT_MR) AS AVG_PCT_PTS_2PT_MR,
    AVG(PCT_PTS_3PT) AS AVG_PCT_PTS_3PT,
    AVG(PCT_PTS_FB) AS AVG_PCT_PTS_FB,
    AVG(PCT_PTS_FT) AS AVG_PCT_PTS_FT,
    AVG(PCT_PTS_OFF_TOV) AS AVG_PCT_PTS_OFF_TOV,
    AVG(PCT_PTS_PAINT) AS AVG_PCT_PTS_PAINT,
    AVG(PCT_AST_2PM) AS AVG_PCT_AST_2PM,
    AVG(PCT_UAST_2PM) AS AVG_PCT_UAST_2PM,
    AVG(PCT_AST_3PM) AS AVG_PCT_AST_3PM,
    AVG(PCT_UAST_3PM) AS AVG_PCT_UAST_3PM,
    AVG(PCT_AST_FGM) AS AVG_PCT_AST_FGM,
    AVG(PCT_UAST_FGM) AS AVG_PCT_UAST_FGM

FROM base.players_combined
GROUP BY PLAYER_ID, SEASON_ID, TEAM_ID
;
