MODEL (
  name base.team_averages,
  kind FULL
);

SELECT
    GAME_ID,
    GAME_DATE,
    SEASON_ID,
    SEASON_TYPE,
    TEAM_ID,
    TEAM_ABBREVIATION,
    TEAM_NAME,
    TEAM_CITY,
    HOME_TEAM,
    AWAY_TEAM,
    IS_HOME,
    MATCHUP,
    LINE,
    OU,
    WL,
    SCORE_DIFF,
    OPP_PTS,
    COVER_RESULT,
    OU_RESULT,
    WINS_SO_FAR,
    LOSSES_SO_FAR,
    LAST_10_WIN_PCT,
    WINS_VS_OPPONENT,
    LOSSES_VS_OPPONENT,
            

		AVG(PTS) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PTS_TO_DATE,
        
        
		AVG(FGM) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FGM_TO_DATE,
        
        
		AVG(FGA) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FGA_TO_DATE,
        
        
		AVG(FG_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FG_PCT_TO_DATE,
        
        
		AVG(FG3M) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FG3M_TO_DATE,
        
        
		AVG(FG3A) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FG3A_TO_DATE,
        
        
		AVG(FG3_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FG3_PCT_TO_DATE,
        
        
		AVG(FTM) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FTM_TO_DATE,
        
        
		AVG(FTA) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FTA_TO_DATE,
        
        
		AVG(FT_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FT_PCT_TO_DATE,
        
        
		AVG(OREB) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OREB_TO_DATE,
        
        
		AVG(DREB) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_DREB_TO_DATE,
        
        
		AVG(REB) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_REB_TO_DATE,
        
        
		AVG(AST) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_AST_TO_DATE,
        
        
		AVG(STL) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_STL_TO_DATE,
        
        
		AVG(BLK) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_BLK_TO_DATE,
        
        
		AVG(TOV) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_TOV_TO_DATE,
        
        
		AVG(PF) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PF_TO_DATE,
        
        
		AVG(PLUS_MINUS) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PLUS_MINUS_TO_DATE,
        
        
		AVG(E_OFF_RATING) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_E_OFF_RATING_TO_DATE,
        
        
		AVG(OFF_RATING) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OFF_RATING_TO_DATE,
        
        
		AVG(E_DEF_RATING) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_E_DEF_RATING_TO_DATE,
        
        
		AVG(DEF_RATING) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_DEF_RATING_TO_DATE,
        
        
		AVG(E_NET_RATING) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_E_NET_RATING_TO_DATE,
        
        
		AVG(NET_RATING) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_NET_RATING_TO_DATE,
        
        
		AVG(AST_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_AST_PCT_TO_DATE,
        
        
		AVG(AST_TOV) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_AST_TOV_TO_DATE,
        
        
		AVG(AST_RATIO) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_AST_RATIO_TO_DATE,
        
        
		AVG(OREB_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OREB_PCT_TO_DATE,
        
        
		AVG(DREB_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_DREB_PCT_TO_DATE,
        
        
		AVG(REB_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_REB_PCT_TO_DATE,
        
        
		AVG(TM_TOV_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_TM_TOV_PCT_TO_DATE,
        
        
		AVG(EFG_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_EFG_PCT_TO_DATE,
        
        
		AVG(TS_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_TS_PCT_TO_DATE,
        
        
		AVG(USG_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_USG_PCT_TO_DATE,
        
        
		AVG(E_USG_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_E_USG_PCT_TO_DATE,
        
        
		AVG(E_PACE) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_E_PACE_TO_DATE,
        
        
		AVG(PACE) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PACE_TO_DATE,
        
        
		AVG(PACE_PER40) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PACE_PER40_TO_DATE,
        
        
		AVG(POSS) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_POSS_TO_DATE,
        
        
		AVG(PIE) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PIE_TO_DATE,
        
        
		AVG(FTA_RATE) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FTA_RATE_TO_DATE,
        
        
		AVG(OPP_EFG_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OPP_EFG_PCT_TO_DATE,
        
        
		AVG(OPP_FTA_RATE) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OPP_FTA_RATE_TO_DATE,
        
        
		AVG(OPP_TOV_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OPP_TOV_PCT_TO_DATE,
        
        
		AVG(OPP_OREB_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OPP_OREB_PCT_TO_DATE,
        
        
		AVG(PTS_OFF_TOV) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PTS_OFF_TOV_TO_DATE,
        
        
		AVG(PTS_2ND_CHANCE) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PTS_2ND_CHANCE_TO_DATE,
        
        
		AVG(PTS_FB) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PTS_FB_TO_DATE,
        
        
		AVG(PTS_PAINT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PTS_PAINT_TO_DATE,
        
        
		AVG(OPP_PTS_OFF_TOV) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OPP_PTS_OFF_TOV_TO_DATE,
        
        
		AVG(OPP_PTS_2ND_CHANCE) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OPP_PTS_2ND_CHANCE_TO_DATE,
        
        
		AVG(OPP_PTS_FB) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OPP_PTS_FB_TO_DATE,
        
        
		AVG(OPP_PTS_PAINT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OPP_PTS_PAINT_TO_DATE,
        
        
		AVG(BLKA) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_BLKA_TO_DATE,
        
        
		AVG(PFD) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PFD_TO_DATE,
        
        
		AVG(PCT_FGA_2PT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_FGA_2PT_TO_DATE,
        
        
		AVG(PCT_FGA_3PT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_FGA_3PT_TO_DATE,
        
        
		AVG(PCT_PTS_2PT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_PTS_2PT_TO_DATE,
        
        
		AVG(PCT_PTS_2PT_MR) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_PTS_2PT_MR_TO_DATE,
        
        
		AVG(PCT_PTS_3PT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_PTS_3PT_TO_DATE,
        
        
		AVG(PCT_PTS_FB) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_PTS_FB_TO_DATE,
        
        
		AVG(PCT_PTS_FT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_PTS_FT_TO_DATE,
        
        
		AVG(PCT_PTS_OFF_TOV) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_PTS_OFF_TOV_TO_DATE,
        
        
		AVG(PCT_PTS_PAINT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_PTS_PAINT_TO_DATE,
        
        
		AVG(PCT_AST_2PM) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_AST_2PM_TO_DATE,
        
        
		AVG(PCT_UAST_2PM) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_UAST_2PM_TO_DATE,
        
        
		AVG(PCT_AST_3PM) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_AST_3PM_TO_DATE,
        
        
		AVG(PCT_UAST_3PM) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_UAST_3PM_TO_DATE,
        
        
		AVG(PCT_AST_FGM) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_AST_FGM_TO_DATE,
        
        
		AVG(PCT_UAST_FGM) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_UAST_FGM_TO_DATE
        


FROM base.teams_processed;