MODEL (
  name base.team_averages,
  kind FULL
);

SELECT
    SEASON_ID,
    SEASON_TYPE,
    TEAM_ID,
    TEAM_ABBREVIATION,
    TEAM_NAME,
    TEAM_CITY,
    NEXT_GAME_ID,
    GAME_ID,
    GAME_NUMBER,
    IS_LAST_TEAM_GAME,
    GAME_DATE,
    MATCHUP,
    HOME_TEAM,
    AWAY_TEAM,
    IS_HOME,
    LINE,
    OU,
    WL,
    SCORE_DIFF,
    OPP_PTS,
    COVER_RESULT,
    OU_RESULT,
    WINS_SO_FAR,
    LOSSES_SO_FAR,
    LAST_10_WIN_PCT,
    WINS_VS_OPPONENT,
    LOSSES_VS_OPPONENT,
            

		AVG(PTS) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PTS,
        
        
		AVG(FGM) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FGM,
        
        
		AVG(FGA) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FGA,
        
        
		AVG(FG_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FG_PCT,
        
        
		AVG(FG3M) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FG3M,
        
        
		AVG(FG3A) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FG3A,
        
        
		AVG(FG3_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FG3_PCT,
        
        
		AVG(FTM) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FTM,
        
        
		AVG(FTA) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FTA,
        
        
		AVG(FT_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FT_PCT,
        
        
		AVG(OREB) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OREB,
        
        
		AVG(DREB) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_DREB,
        
        
		AVG(REB) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_REB,
        
        
		AVG(AST) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_AST,
        
        
		AVG(STL) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_STL,
        
        
		AVG(BLK) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_BLK,
        
        
		AVG(TOV) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_TOV,
        
        
		AVG(PF) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PF,
        
        
		AVG(PLUS_MINUS) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PLUS_MINUS,
        
        
		AVG(E_OFF_RATING) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_E_OFF_RATING,
        
        
		AVG(OFF_RATING) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OFF_RATING,
        
        
		AVG(E_DEF_RATING) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_E_DEF_RATING,
        
        
		AVG(DEF_RATING) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_DEF_RATING,
        
        
		AVG(E_NET_RATING) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_E_NET_RATING,
        
        
		AVG(NET_RATING) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_NET_RATING,
        
        
		AVG(AST_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_AST_PCT,
        
        
		AVG(AST_TOV) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_AST_TOV,
        
        
		AVG(AST_RATIO) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_AST_RATIO,
        
        
		AVG(OREB_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OREB_PCT,
        
        
		AVG(DREB_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_DREB_PCT,
        
        
		AVG(REB_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_REB_PCT,
        
        
		AVG(TM_TOV_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_TM_TOV_PCT,
        
        
		AVG(EFG_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_EFG_PCT,
        
        
		AVG(TS_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_TS_PCT,
        
        
		AVG(USG_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_USG_PCT,
        
        
		AVG(E_USG_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_E_USG_PCT,
        
        
		AVG(E_PACE) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_E_PACE,
        
        
		AVG(PACE) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PACE,
        
        
		AVG(PACE_PER40) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PACE_PER40,
        
        
		AVG(POSS) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_POSS,
        
        
		AVG(PIE) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PIE,
        
        
		AVG(FTA_RATE) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_FTA_RATE,
        
        
		AVG(OPP_EFG_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OPP_EFG_PCT,
        
        
		AVG(OPP_FTA_RATE) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OPP_FTA_RATE,
        
        
		AVG(OPP_TOV_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OPP_TOV_PCT,
        
        
		AVG(OPP_OREB_PCT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OPP_OREB_PCT,
        
        
		AVG(PTS_OFF_TOV) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PTS_OFF_TOV,
        
        
		AVG(PTS_2ND_CHANCE) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PTS_2ND_CHANCE,
        
        
		AVG(PTS_FB) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PTS_FB,
        
        
		AVG(PTS_PAINT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PTS_PAINT,
        
        
		AVG(OPP_PTS_OFF_TOV) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OPP_PTS_OFF_TOV,
        
        
		AVG(OPP_PTS_2ND_CHANCE) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OPP_PTS_2ND_CHANCE,
        
        
		AVG(OPP_PTS_FB) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OPP_PTS_FB,
        
        
		AVG(OPP_PTS_PAINT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_OPP_PTS_PAINT,
        
        
		AVG(BLKA) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_BLKA,
        
        
		AVG(PFD) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PFD,
        
        
		AVG(PCT_FGA_2PT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_FGA_2PT,
        
        
		AVG(PCT_FGA_3PT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_FGA_3PT,
        
        
		AVG(PCT_PTS_2PT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_PTS_2PT,
        
        
		AVG(PCT_PTS_2PT_MR) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_PTS_2PT_MR,
        
        
		AVG(PCT_PTS_3PT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_PTS_3PT,
        
        
		AVG(PCT_PTS_FB) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_PTS_FB,
        
        
		AVG(PCT_PTS_FT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_PTS_FT,
        
        
		AVG(PCT_PTS_OFF_TOV) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_PTS_OFF_TOV,
        
        
		AVG(PCT_PTS_PAINT) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_PTS_PAINT,
        
        
		AVG(PCT_AST_2PM) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_AST_2PM,
        
        
		AVG(PCT_UAST_2PM) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_UAST_2PM,
        
        
		AVG(PCT_AST_3PM) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_AST_3PM,
        
        
		AVG(PCT_UAST_3PM) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_UAST_3PM,
        
        
		AVG(PCT_AST_FGM) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_AST_FGM,
        
        
		AVG(PCT_UAST_FGM) OVER (
        PARTITION BY SEASON_ID, TEAM_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS AVG_PCT_UAST_FGM
        


FROM base.teams_processed;