MODEL (
  name aggs.player_sums,
  kind FULL
);

SELECT
    PLAYER_ID,
    SEASON_ID,
    TEAM_ID,
    GAME_ID,
    NEXT_GAME_ID,
    GAME_DATE,
    PLAYER_NAME,
    TEAM_NAME,

    -- Cumulative Games Played (up to and including this game)
    GAME_COUNT,
    GAMES_PLAYED,
    PLAYED_FLAG,
    IS_LAST_GAME,
    -- Cumulative Minutes
    SUM(
        MINUTES
    ) OVER (
        PARTITION BY PLAYER_ID, SEASON_ID
        ORDER BY CAST(GAME_DATE AS DATE)
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS MINUTES_CUMULATIVE,

    -- Cumulative Points

        
SUM(PTS) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS PTS_CUMULATIVE,
        
        
SUM(AST) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS AST_CUMULATIVE,
        
        
SUM(REB) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS REB_CUMULATIVE,
        
        
SUM(OREB) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS OREB_CUMULATIVE,
        
        
SUM(DREB) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS DREB_CUMULATIVE,
        
        
SUM(STL) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS STL_CUMULATIVE,
        
        
SUM(BLK) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS BLK_CUMULATIVE,
        
        
SUM(PF) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS PF_CUMULATIVE,


SUM("TO") OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS TO_CUMULATIVE,
        
        
SUM(FGM) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS FGM_CUMULATIVE,
        
        
SUM(FGA) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS FGA_CUMULATIVE,
        
        
SUM(FG3M) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS FG3M_CUMULATIVE,
        
        
SUM(FG3A) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS FG3A_CUMULATIVE,
        
        
SUM(FTM) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS FTM_CUMULATIVE,
        
        
SUM(FTA) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS FTA_CUMULATIVE,
        
        
SUM(PLUS_MINUS) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS PLUS_MINUS_CUMULATIVE,
        
        
SUM(PTS_OFF_TOV) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS PTS_OFF_TOV_CUMULATIVE,
        
        
SUM(PTS_2ND_CHANCE) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS PTS_2ND_CHANCE_CUMULATIVE,
        
        
SUM(PTS_FB) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS PTS_FB_CUMULATIVE,
        
        
SUM(PTS_PAINT) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS PTS_PAINT_CUMULATIVE,
        
        
SUM(OPP_PTS_OFF_TOV) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS OPP_PTS_OFF_TOV_CUMULATIVE,
        
        
SUM(OPP_PTS_2ND_CHANCE) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS OPP_PTS_2ND_CHANCE_CUMULATIVE,
        
        
SUM(OPP_PTS_FB) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS OPP_PTS_FB_CUMULATIVE,
        
        
SUM(OPP_PTS_PAINT) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS OPP_PTS_PAINT_CUMULATIVE,
        
        
SUM(BLKA) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS BLKA_CUMULATIVE,
        
        
SUM(PFD) OVER (
                PARTITION BY PLAYER_ID, SEASON_ID
                ORDER BY CAST(GAME_DATE AS DATE)
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS PFD_CUMULATIVE,
        

FROM base.players_processed
-- WHERE PLAYER_ID IS NOT NULL
ORDER BY PLAYER_ID, SEASON_ID, CAST(GAME_DATE AS DATE)
;
